[package]
name = "sapio"
version = "0.1.0"
authors = ["Jeremy Rubin <j@rubin.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.miniscript]
git="file:///home/jr/develop/judica/rust-miniscript"
branch="ctv-support-2"
features = ['compiler', 'use-serde', 'rand']

[dependencies]
lazy_static = "*"
schemars = "0.8.0"
serde_json = "1.0"
[dependencies.bitcoin]
version = "0.24"
features = ['use-serde', 'rand']
