[workspace]
members = ["sapio", "sapio-ws", "sapio-front", "sapio-contrib", "ctv_emulators", "sapio-base", "cli", "tools", "plugins", 'emulator-trait']
exclude = ["plugin-example", "integration_tests"]
