[package]
name = "sapio"
version = "0.1.0"
authors = ["Jeremy Rubin <j@rubin.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies.miniscript]
version = "2.0.1"
features = ['compiler', 'use-serde', 'rand', 'use-schemars', 'serde']

[features]
# used to enable some niceties if compiling on a nightly compiler
nightly = []

[dependencies]
schemars = "0.8.0"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"

[dependencies.bitcoin]
version = "0.25"
features = ['use-serde', 'rand']

