# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Sapio Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up Rust Stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build Rust Miniscript
      run: |
          cd rust_miniscript && make
        
    - name: Lint with flake8
      run: |
        flake8 --ignore=E203,E226,E402,E501,E722,E741,F401,F403,F405,F821,W503,W504 --count --show-source --statistics $(git ls-files -- "*.py")
    
    - name: Install modules
      run: |
        for MODULE in sapio_bitcoinlib rust_miniscript bitcoin_script_compiler sapio_compiler sapio_stdlib sapio_zoo sapio_server; do
          echo "Building ${MODULE}"
          cd $MODULE && make && python3 setup.py build && python3 setup.py install && cd ..
        done
        
    - name: Run unit tests
      run: |
        make test
